server:
  port: 8089

spring:
  application:
    name: hotSearch # 项目名
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotsearch?useSSL=false&serverTimezone=UTC         #云端数据库
    username: hotsearch
    password: X3fFaAJKiAEhpJeA
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000
      idle-timeout: 600000

mybatis-plus:
  #  mapper-locations: classpath*:/**/mapper/**/*.xml
  #  type-aliases-package: com.itchen.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL日志
    use-default-exception: true
  global-config: # 全局配置，数据库配置
    db-config:
      id-type: auto    # 主键id生成策略，auto，根据数据库类型自动选择
      #      field-strategy: not_empty    # 字段填充策略，not_empty 表示只有当字段不为空时，才会进行字段填充
      #      logic-delete-value: 1        # 逻辑删除值
      #      logic-not-delete-value: 0    # 逻辑未删除值
      batch-size: 1000
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 5
        min-idle: 1 # 连接池中最大空闲连接数
        max-idle: 3 # 连接池中最大空闲连接数
        max-wait: 30000ms # 获取连接时的最大等待毫秒数
    port: 6379
    timeout: 10000ms
  #    password: