server:
  port: 8089

spring:
  application:
    name: hotSearch # 项目名

  datasource:
    url: jdbc:mysql://81.69.46.160:3306/parking         #本地数据库
    username: root
    password: lanlan1212!@#
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000
      idle-timeout: 600000

# mybatis打印日志
logging:
  level:
    com:
      itchen:
        hospital:
          mapper: info
# 在Mybatis-Plus配置中增加
mybatis-plus:
  global-config:
    db-config:
      batch-size: 1000
